#pragma once

#define WIN32_LEAN_AND_MEAN 

#include <Windows.h>
#include <vector>
#include <string>
#include <map>
#include <d2d1.h>
#include <mathtypes.h>
const color_m color_junk = color_m{0.5f, 0.5f, 0.5f, 1.f};              // Grey
const color_m color_poor = color_m{0.3f, 0.3f, 0.3f, 1.f};              // Dark Grey
const color_m color_common = color_m{0.2f, 0.2f, 0.2f, 1.f};            // Darker Grey
const color_m color_uncommon = color_m{0.0f, 1.0f, 0.0f, 1.f};        // Light Green
const color_m color_epic = color_m{0.5f, 0.0f, 1.0f, 1.f};              // Purple
const color_m color_rare = color_m{0.0f, 0.0f, 1.0f, 1.f};              // Blue
const color_m color_legendary = color_m{1.0f, 1.0f, 0.0f, 1.f};

// Create an unordered map to associate rarity strings with colors
inline std::map<std::string, color_m> rarity_colors{
    { "Type.Item.Rarity.Junk", color_junk },
    { "Type.Item.Rarity.Poor", color_poor },
    { "Type.Item.Rarity.Common", color_common },
    { "Type.Item.Rarity.Uncommon", color_uncommon },
    { "Type.Item.Rarity.Epic", color_epic },
    { "Type.Item.Rarity.Rare", color_rare },
    { "Type.Item.Rarity.Legendary", color_legendary }
};

inline std::map<std::string, std::string> rarities{
    { "Type.Item.Rarity.Junk", "Junk" },
    { "Type.Item.Rarity.Poor", "Poor" },
    { "Type.Item.Rarity.Common", "Common" },
    { "Type.Item.Rarity.Uncommon", "Uncommon" },
    { "Type.Item.Rarity.Epic", "Epic" },
    { "Type.Item.Rarity.Rare", "Rare" },
    { "Type.Item.Rarity.Legend", "Legendary" },
};
inline std::vector<std::string> socket_names = {
        "CS_left?Ch=Event.Attack.Collision.On.01",
        "CS_left_0?Ch=Event.Attack.Collision.On.01",
        "CS_left_1?Ch=Event.Attack.Collision.On.01",
        "CS_left_2?Ch=Event.Attack.Collision.On.01",
        "CS_right?Ch=Event.Attack.Collision.On.02",
        "CS_right_0?Ch=Event.Attack.Collision.On.02",
        "CS_right_1?Ch=Event.Attack.Collision.On.02",
        "CS_right_2?Ch=Event.Attack.Collision.On.02",
        "sheath_back_01",
        "sheath_back_left_01",
        "sheath_back_pelvis_01",
        "sheath_back_right_01",
        "sheath_thigh_l_01",
        "eye_l",
        "eye_r",
        "potion_pelvis_01",
        "potion_pelvis_02",
        "potion_pelvis_03",
        "CS_left?Ch=Event.Attack.Collision.On.Stuck.Secondary",
        "CS_left_0?Ch=Event.Attack.Collision.On.Stuck.Secondary",
        "CS_left_1?Ch=Event.Attack.Collision.On.Stuck.Secondary",
        "CS_left_2?Ch=Event.Attack.Collision.On.Stuck.Secondary",
        "CS_right?Ch=Event.Attack.Collision.On.Stuck.Primary",
        "CS_right_0?Ch=Event.Attack.Collision.On.Stuck.Primary",
        "CS_right_1?Ch=Event.Attack.Collision.On.Stuck.Primary",
        "CS_right_2?Ch=Event.Attack.Collision.On.Stuck.Primary",
        "CS_left_3?Ch=Event.Attack.Collision.On.Stuck.Secondary",
        "CS_left_4?Ch=Event.Attack.Collision.On.Stuck.Secondary",
        "CS_left_5?Ch=Event.Attack.Collision.On.Stuck.Secondary",
        "CS_left_6?Ch=Event.Attack.Collision.On.Stuck.Secondary",
        "CS_right_3?Ch=Event.Attack.Collision.On.Stuck.Primary",
        "CS_right_4?Ch=Event.Attack.Collision.On.Stuck.Primary",
        "CS_right_5?Ch=Event.Attack.Collision.On.Stuck.Primary",
        "CS_right_6?Ch=Event.Attack.Collision.On.Stuck.Primary",
        "sheath_back_center_04",
        "sheath_back_center_03",
        "sheath_pelvis_r_02",
        "campfirekit_pelvis",
        "sheath_back_pelvis_02",
        "sheath_back_left_02",
        "sheath_back_center_01",
        "sheath_back_center_06",
        "FX_AboveBody",
        "quiver_socket_01",
        "sheath_back_center_02",
        "sheath_back_left_03",
        "FX_Chest_Left",
        "sheath_thigh_r_02",
        "sheath_thigh_r_01",
        "sheath_pelvis_l_01",
        "sheath_pelvis_drum",
        "sheath_back_center_05",
        "calf_Twine_l",
        "calf_Twine_r",
        "sheath_pelvis_bandage",
        "Root",
        "pelvis",
        "spine_01",
        "spine_02",
        "spine_03",
        "clavicle_l",
        "upperarm_l",
        "lowerarm_l",
        "hand_l",
        "thumb_01_l",
        "thumb_02_l",
        "thumb_03_l",
        "index_01_l",
        "index_02_l",
        "index_03_l",
        "middle_01_l",
        "middle_02_l",
        "middle_03_l",
        "ring_01_l",
        "ring_02_l",
        "ring_03_l",
        "pinky_01_l",
        "pinky_02_l",
        "pinky_03_l",
        "fk_weapon_l",
        "shield_l",
        "lowerarm_twist_01_l",
        "upperarm_twist_01_l",
        "neck_01",
        "Head",
        "eyelid_l",
        "eyelid_r",
        "clavicle_r",
        "upperarm_r",
        "lowerarm_r",
        "lowerarm_twist_01_r",
        "shield_r",
        "hand_r",
        "pinky_01_r",
        "pinky_02_r",
        "pinky_03_r",
        "ring_01_r",
        "ring_02_r",
        "ring_03_r",
        "middle_01_r",
        "middle_02_r",
        "middle_03_r",
        "index_01_r",
        "index_02_r",
        "index_03_r",
        "thumb_01_r",
        "thumb_02_r",
        "thumb_03_r",
        "fk_weapon_r",
        "upperarm_twist_01_r",
        "thigh_l",
        "calf_l",
        "foot_l",
        "ball_l",
        "calf_twist_01_l",
        "thigh_twist_01_l",
        "thigh_r",
        "calf_r",
        "foot_r",
        "ball_r",
        "calf_twist_01_r",
        "thigh_twist_01_r",
        "ik_foot_root",
        "ik_foot_l",
        "ik_foot_r",
        "ik_hand_root",
        "ik_hand_gun",
        "ik_hand_l",
        "weapon_l",
        "ik_hand_r",
        "weapon_r",
        "camera_root",
        "camera_rot_root",
        "Camera"
};

inline std::vector<std::pair<std::string, std::string>> socket_skeleton = {
    { "spine_01", "spine_02" },
    { "spine_02", "spine_03" },
    { "spine_03", "clavicle_l" },
    { "spine_03", "clavicle_r" },
    { "clavicle_l", "upperarm_l" },
    { "clavicle_r", "upperarm_r" },
    { "upperarm_l", "lowerarm_l" },
    { "upperarm_r", "lowerarm_r" },
    { "lowerarm_l", "hand_l" },
    { "lowerarm_r", "hand_r" },
    { "spine_02", "neck_01" },
    { "neck_01", "Head" },
    { "pelvis", "thigh_l" },
    { "pelvis", "thigh_r" },
    { "pelvis", "spine_01" },
    { "thigh_l", "calf_l" },
    { "thigh_r", "calf_r" },
    { "calf_l", "foot_l" },
    { "calf_r", "foot_r" }
};
